version: '3'
services:

  drupal:
    user: "${DAO_DRUPAL}"
    image:  siva01/drupal_php7.3
    env_file:
      - .env
    volumes:  [ "${DAO_PROJECT_DIR}:/var/www/html:delegated" ]

  adminer:
    image: adminer:latest
    ports: [ "${DAO_PORT_ADMINER}:8080" ]

  nginx:
    user: "${DAO_DRUPAL}"
    image: siva01/drupal-nginx
    ports: [ "${DAO_PORT_NGINX}:8080" ]
    volumes:  [ "${DAO_PROJECT_DIR}:/var/www/html:delegated" ]

  mysql:
    image:  mysql:5.7.31
    ports: [ "${DAO_PORT_MYSQL}:3306" ]
    environment:
      MYSQL_ROOT_PASSWORD: "${DAO_MYSQL_ROOT_PASSWORD}"
    volumes: [ "/var/lib/mysql" ]
